---
title: "Chapter 3 - Basic Data Management"
output: html_notebook
---

```{r load}
library(dplyr)
```

```{r 3.7}

manager <- c(1, 2, 3, 4, 5)
date <- c("10/24/08", "10/28/08", "10/1/08", "10/12/08", "5/1/09")
country <- c("US", "US", "UK", "UK", "UK")
gender <- c("M", "F", "F", "M", "F")
age <- c(32, 45, 25, 39, 99)
q1 <- c(5, 3, 3, 3, 2)
q2 <- c(4, 5, 5, 3, 2)
q3 <- c(5, 2, 5, 4, 1)
q4 <- c(5, 5, 5, NA, 2)
q5 <- c(5, 5, 2, NA, 1)
leadership <- data.frame(manager, date, country, gender, age,
                         q1, q2, q3, q4, q5, stringsAsFactors=FALSE)
```

```{r pipes}

leadership <- mutate(leadership,
                     total_score = q1 + q2 + q3 + q4 + q5,
                     mean_score = total_score / 5)
 
leadership$gender <- recode(leadership$gender,
                            "M" = "male", "F" = "female")

leadership %<>%
  rename(ID = "manager", sex = "gender") %>%
  arrange(sex, total_score)

# equivalent to what's above. 
#leadership <- rename(leadership,ID = "manager", sex = "gender") %> 
#  arrange(sex, total_score)

leadership_ratings <-  select(leadership, ID, mean_score) 
leadership_men_high <- filter(leadership, sex == "male" & total_score > 10)

```

