---
title: "Chapter 7 - Basic Statistics"
output: html_notebook
---

```{r install}
install.packages(c("Hmisc", "pastecs", "psych", "carData"))
install.packages(c("vcd"))

```


```{r load}
#laod built in dataset.
data(mtcars)
library(Hmisc)
library(psych)
library(pastecs)
```


```{r}
myvars <- c("mpg", "hp", "wt")
head(mtcars[myvars])
```

```{r}
summary(mtcars[myvars])
```

```{r}
mystats <- function(x, na.omit=FALSE) {
  if(na.omit)
    x <- x[!is.na(x)]
  m <- mean(x)
  n <- length(x)
  s <- sd(x)
  return(c(n=n, mean=m, stdev=s))
}

sapply( mtcars[myvars], mystats)
```

```{r}
#from Hmisc - seeing messages it's "masked"
Hmisc::describe(mtcars[myvars])
```

### Summary stats by group

Reminds me of "GROUP BY" in SQL. 

```{r}
dstats <- function(x) sapply(x, mystats)
by(mtcars[myvars], mtcars$am, dstats)
```

```{r}
dstats <- function(x) sapply(x, mystats, na.omit=TRUE)
by(mtcars[myvars], list(Transmission=mtcars$am, Engine=mtcars$vs), FUN=dstats)
```

### More experimenting with sapply

```{r}
justthemean <- function(x, na.omit=FALSE) {
  mean(x) #last expression automatically returned.
}

mn <- sapply(mtcars, justthemean, na.omit=TRUE) #will return a vector. 
```

### Messing with 'summarize'

```{r}
library(dplyr)
library(carData)
```

```{r}
Salaries %>%
  summarise(med = median(salary),
            min = min(salary))
```
 
```{r}
Salaries %>%
  group_by(rank, sex) %>%
  select(yrs.since.phd, yrs.service) %>%
  summarize_all(list(mean, max))
```
 
 ### Frequency and Contingency
 
```{r}
library(vcd)
```
```{r}
head(Arthritis)
```
 
```{r}
mytable <- with(Arthritis, table(Improved))
# same as
# table(Arthritis$Improved)
prop.table(mytable) #freq -> proportions
```
 
```{r}
#contingency table from formula
tvi <- xtabs(~ Treatment+Improved, data=Arthritis)
```
 
```{r}
prop.table(tvi)
```
 
```{r}
margin.table(tvi, 1)
```
 
```{r}
margin.table(tvi, 2)
```
 
 ### Chi-Squared Test

Testing for independence of categorical variables. 
 
```{r}
#treatment vs improved. 
chisq.test(tvi)
# note the p-value (chance of observing this association if the null hypothesis holds) is very low. 
```
 
```{r}
svi <- xtabs(~ Sex + Improved, data=Arthritis)
chisq.test(svi)
# less of a relationship but still some evidence of association. 
```
 
 